services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notes"]
      interval: 5s
      timeout: 5s
      retries: 10

  note-tracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "postgres://user:password@db:5432/notes?sslmode=disable"
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      db:
        condition: service_healthy